### ISSUE TITLE
about the disasemble..

### ISSUE THREAD

**Issue by shevc08** [twisteroidambassador/llsifclient#2]
hi,
sorry to disturb, i read about the issue #1 , but i still trapped in the disassemble..
as i disassembled the libgame.so ,i found this : 

DELETED...

i think this is the function , but i can't figure out which one is the input argument ,or , maybe i found the wrong place ?

since I have little knowledge of assemble, it would be very appricated if you could give some hints ,thank you.

**Comment by twisteroidambassador** [comment]
I would rather not give a lecture on disassembly here, so you're mostly on your own. 

There are two things you absolutely have to understand in order to work this out: how to pass function arguments around in assembly, and how to write a C function that takes several variable length strings as arguments. Then, look out for the string "X-Message-Code". Good luck!

**Comment by shevc08** [comment]
problem solved,thank you very much !!

**Comment by shevc08** [comment]
problem solved,thank you very much !!
